<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260901170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Synchronize PostgreSQL defaults, constraints and Messenger transport indexes with Doctrine metadata';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE delivery_attempt ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE delivery_attempt ALTER updated_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER INDEX delivery_attempt_order_id_key RENAME TO UNIQ_12F2BDB88D9F6D38');
        $this->addSql('ALTER TABLE promo_redemption ALTER id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE promo_redemption_id_seq');
        $this->addSql('ALTER TABLE promo_redemption ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql("SELECT setval(pg_get_serial_sequence('promo_redemption', 'id'), COALESCE(MAX(id), 0) + 1, false) FROM promo_redemption");
        $this->addSql('ALTER TABLE promo_redemption ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER INDEX promo_redemption_order_id_key RENAME TO UNIQ_70FA94408D9F6D38');
        $this->addSql('ALTER TABLE inventory_key ALTER id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE inventory_key_id_seq');
        $this->addSql('ALTER TABLE inventory_key ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql("SELECT setval(pg_get_serial_sequence('inventory_key', 'id'), COALESCE(MAX(id), 0) + 1, false) FROM inventory_key");
        $this->addSql('ALTER INDEX inventory_key_code_key RENAME TO UNIQ_F3FAC4CD77153098');
        $this->addSql('ALTER INDEX inventory_key_assigned_order_id_key RENAME TO UNIQ_F3FAC4CDF0926B31');
        $this->addSql('ALTER TABLE payment_event ALTER received_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE purchase_order ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE purchase_order ALTER updated_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER INDEX purchase_order_client_request_id_key RENAME TO UNIQ_21E210B2D22A85E4');
        $this->addSql('ALTER TABLE supplier_issue ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER INDEX supplier_issue_order_unique_idx RENAME TO UNIQ_CBB621148D9F6D38');
        $this->addSql('ALTER INDEX supplier_issue_inventory_key_id_key RENAME TO UNIQ_CBB62114DC8C998');
        $this->addSql('DROP INDEX messenger_messages_queue_idx');
        $this->addSql('DROP INDEX messenger_messages_available_idx');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE messenger_messages_id_seq');
        $this->addSql('ALTER TABLE messenger_messages ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql("SELECT setval(pg_get_serial_sequence('messenger_messages', 'id'), COALESCE(MAX(id), 0) + 1, false) FROM messenger_messages");
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP IDENTITY IF EXISTS');
        $this->addSql('CREATE SEQUENCE messenger_messages_id_seq');
        $this->addSql("SELECT setval('messenger_messages_id_seq', COALESCE(MAX(id), 0) + 1, false) FROM messenger_messages");
        $this->addSql('ALTER SEQUENCE messenger_messages_id_seq OWNED BY messenger_messages.id');
        $this->addSql("ALTER TABLE messenger_messages ALTER id SET DEFAULT nextval('messenger_messages_id_seq'::regclass)");
        $this->addSql('CREATE INDEX messenger_messages_queue_idx ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX messenger_messages_available_idx ON messenger_messages (available_at)');
        $this->addSql('ALTER INDEX UNIQ_CBB62114DC8C998 RENAME TO supplier_issue_inventory_key_id_key');
        $this->addSql('ALTER INDEX UNIQ_CBB621148D9F6D38 RENAME TO supplier_issue_order_unique_idx');
        $this->addSql('ALTER TABLE supplier_issue ALTER created_at SET DEFAULT NOW()');
        $this->addSql('ALTER INDEX UNIQ_21E210B2D22A85E4 RENAME TO purchase_order_client_request_id_key');
        $this->addSql('ALTER TABLE purchase_order ALTER updated_at SET DEFAULT NOW()');
        $this->addSql('ALTER TABLE purchase_order ALTER created_at SET DEFAULT NOW()');
        $this->addSql('ALTER TABLE payment_event ALTER received_at SET DEFAULT NOW()');
        $this->addSql('ALTER INDEX UNIQ_F3FAC4CDF0926B31 RENAME TO inventory_key_assigned_order_id_key');
        $this->addSql('ALTER INDEX UNIQ_F3FAC4CD77153098 RENAME TO inventory_key_code_key');
        $this->addSql('ALTER TABLE inventory_key ALTER id DROP IDENTITY IF EXISTS');
        $this->addSql('CREATE SEQUENCE inventory_key_id_seq');
        $this->addSql("SELECT setval('inventory_key_id_seq', COALESCE(MAX(id), 0) + 1, false) FROM inventory_key");
        $this->addSql('ALTER SEQUENCE inventory_key_id_seq OWNED BY inventory_key.id');
        $this->addSql("ALTER TABLE inventory_key ALTER id SET DEFAULT nextval('inventory_key_id_seq'::regclass)");
        $this->addSql('ALTER INDEX UNIQ_70FA94408D9F6D38 RENAME TO promo_redemption_order_id_key');
        $this->addSql('ALTER TABLE promo_redemption ALTER created_at SET DEFAULT NOW()');
        $this->addSql('ALTER TABLE promo_redemption ALTER id DROP IDENTITY IF EXISTS');
        $this->addSql('CREATE SEQUENCE promo_redemption_id_seq');
        $this->addSql("SELECT setval('promo_redemption_id_seq', COALESCE(MAX(id), 0) + 1, false) FROM promo_redemption");
        $this->addSql('ALTER SEQUENCE promo_redemption_id_seq OWNED BY promo_redemption.id');
        $this->addSql("ALTER TABLE promo_redemption ALTER id SET DEFAULT nextval('promo_redemption_id_seq'::regclass)");
        $this->addSql('ALTER INDEX UNIQ_12F2BDB88D9F6D38 RENAME TO delivery_attempt_order_id_key');
        $this->addSql('ALTER TABLE delivery_attempt ALTER updated_at SET DEFAULT NOW()');
        $this->addSql('ALTER TABLE delivery_attempt ALTER created_at SET DEFAULT NOW()');
    }
}
